name: deployscp
on:
  push:
    branches: [ master ]

jobs:
  deploy:    
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Deploy source-code
        uses: appleboy/scp-action@v0.1.4
        with:
          host: 3.111.150.192
          username: Administrator
          password: o8(dqi$aY-*zLrFgL&l42Eef$z4%Y)oy
          port: 22
          source: "*"
          target: C:\Users\Administrator\Desktop\new
      
