name: deployscp
on:
  push:
    branches: [ master ]

jobs:
  deploy:    
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Deploy source-code
        uses: appleboy/scp-action@v0.1.4
        with:
          HOST: ${{ secrets.SSH_HOST }}
          USERNAME: ${{ secrets.SSH_USERNAME }}
          PORT: 22
          KEY: ${{ secrets.SSH_KEY }}
          source: "*"
          target: "/var/www/html/"
