name: CI-SFTP

# Controls when the action will run. 
on:
  push:
    branches: [ master]
  workflow_dispatch:

jobs:
  # This workflow contains a single job called "SFTP" it will connect with dev server and upload files on server
  deploy-via-sftp:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Get latest code
      uses: actions/checkout@v2
    
    - name: Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.3.3
      with:
        server: 13.233.9.70
        username: ubuntu
        password: ${{ secrets.MASTER_PASSWORD }}
        exclude: |
          .htaccess
          **/.git*
          **/.git*/**
