name: scp files
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: copy file via ssh password
      uses: appleboy/scp-action@master
      with:
        host: 13.234.231.222
        username: ubuntu
        password: ${{ secrets.MASTER_PASSWORD }}
        port: 22
        source: "/assets,/index.html"
        target: /var/www/html
